@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}

POST {{host}}/api/v1/auth/register
Content-Type: application/json

{
    "email": "karim@gmail.com",
    "username": "omranekarim",
    "password": "Toto2024*-1"
}

###

POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "karim@gmail.com",
    "password": "Toto2024*-1"
}