@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}

GET {{host}}/api/v1/user/get-others
x-access-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjU5ZWVjZTE4OWI1ZTA3ZDI1NWU1ZTk3IiwiZW1haWwiOiJrYXJpbUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTcwNDkxNDE5NSwiZXhwIjoxNzA3NTA2MTk1fQ.HOz4G7YHHOAZIFdIHFhPXKP7D250uLz-8fg8Vv6Teog

